config/routes.rb
Rails.application.routes.draw do
  resources :achievements, only: [ :new, :create, :show ]
  root to: 'welcome#index'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  validates :title, presence: true
  enum privacy: [ :public_access, :private_access, :friends_access ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = Achievement.new(achievement_params)
    if @achievement.save
      redirect_to root_url, notice: 'achievement has been created'
    else
      render :new
    end
  end

  def show
    @achievement = Achievement.find(params[:id])
    @description = Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(@achievement.description)
  end

  private

  def achievement_params
    params.require(:achievement).permit(:title, :description, :privacy, :cover_image, :featured)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/achievements/new.html.erb
<%= simple_form_for @achievement do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :privacy, collection: Hash[Achievement.privacies.map { |k,v| [ k.split(',').first.capitalize, k ]}] %>
  <%= f.input :featured, label: 'feature achievement' %>
  <%= f.input :cover_image, as: :file %>
  <%= f.submit 'create achievement', class: 'btn btn-primary' %>
<% end %>

app/views/achievements/show.html.erb
<h1><%= @achievement.title %></h1>
<div>
  <%= @description.html_safe %>
</div>

app/views/layouts/application.html.erb
l<!DOCTYPE html>
<html>
  <head>
    <title>PluralsightTdd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <nav>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'new achievement', new_achievement_path %></li>
          </ul>
        </div>
      </nav>

      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>